version: '3'

services:
    backend:
        tty: true
        stdin_open: true
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        # Mapping Container PORT 8000 to Host PORT 8000
        ports:
            - 8000:8000
        env_file:
            - ./.env
        volumes:
            - './backend/src/:/backend/'
        depends_on:
            - postgres_db


    postgres_db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env

volumes:
    postgres_data:

